version: '3.7'

services:
  # MySQL
    db:
      image: mysql:8.0
      container_name: mysql.8x
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - ~/docker/mysql.8x/data:/var/lib/mysql
        - ~/docker/mysql.8x/files:/var/lib/mysql-files
        - ~/docker/mysql.8x/etc:/etc/mysql/conf.d:ro
      restart: always
      ports:
        - "3306:3306"
      environment:
        TZ: "Asia/Bangkok"
        MYSQL_DATABASE: "test"
        MYSQL_ROOT_PASSWORD: secret
      networks:
        - dev_network

  # PHP MyAdmin
    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      container_name: myadmin
      restart: always
      ports:
        - "8080:80"
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: secret
      networks:
        - dev_network

networks:
  dev_network:
    driver: bridge
